application: ChietiDj
version: 2
runtime: python27
api_version: 1

threadsafe: true

libraries:
- name: numpy
version: "1.6.1"

handlers:

- url: /favicon.ico
static_files: static/favicon.ico
upload: static/favicon.ico

- url: /static
static_dir: static/static
expiration: 1m

- url: .*
script: mainappengine.app